### ISSUE TITLE
Problem with button on HomeKit 

### ISSUE THREAD

**Issue by ivanx00** [ebaauw/homebridge-rpi#104]
Hi everyone!
I have a big issue with this plug in and HomeKit 
Until today everything worked perfectly but a few minutes ago in the Himekit app the Button (that contained 13 settled button) changed in only one single button programmable.
When this issue I can only set single, double and long press for only one button (and it works with the same set for all the real button that I have all around the house)
Thanks for everyone who has a tip for me 
Ivan

**Comment by ebaauw** [comment]
I'm sorry, I have no idea what you're saying.  Please attach a screenshot and log file to explain what's happening.

**Comment by ivanx00** [comment]
> I'm sorry, I have no idea what you're saying. Please attach a screenshot and log file to explain what's happening.

![ABA1BDE2-051B-4E5E-B735-0F7B00FC94F1](https://user-images.githubusercontent.com/88212307/127713239-75e34397-89e0-4af7-a828-dbc9649deb97.png)
![23151247-861E-4855-8117-42692373A1E2](https://user-images.githubusercontent.com/88212307/127713261-758ac663-1a88-47f8-acc5-59d2e486f265.png)

HomeKit let me set only one button (until yesterday there where all the button in the Home App)

**Comment by ebaauw** [comment]
Did you update iOS?  Or Homebridge or Homebridge RPi?  Or anything else?

Could you please capture and attach a debug log file?  See https://github.com/ebaauw/homebridge-hue/wiki/FAQ#homebridge.

**Comment by ivanx00** [comment]
> Did you update iOS? Or Homebridge or Homebridge RPi? Or anything else?
> 
> Could you please capture and attach a debug log file? See https://github.com/ebaauw/homebridge-hue/wiki/FAQ#homebridge.

No nothing 

[homebridge.log.txt](https://github.com/ebaauw/homebridge-rpi/files/6910188/homebridge.log.txt)

**Comment by ebaauw** [comment]
Done some testing and debugging.  Homebridge RPi sets up the GPIO pins alright, but it creates all buttons (_Stateless Programmable Switch_ services) using the same subtype, so HomeKit only sees one button.  I think this bug was introduced in [v1.1.16](https://github.com/ebaauw/homebridge-rpi/releases/tag/v1.1.16), back in October 2020 to deal with iOS14.  I'll publish a fix later this weekend.

It looks like your accessory cache was cleared around 22:26, causing Homerbridge RPi to re-create the accessories instead of re-using the restored accessories.  I think the multiple buttons might have continued to show, despite the bug, because they were created by an older version (before v1.1.16?).

**Comment by ivanx00** [comment]
> Done some testing and debugging. Homebridge RPi sets up the GPIO pins alright, but it creates all buttons (_Stateless Programmable Switch_ services) using the same subtype, so HomeKit only sees one button. I think this bug was introduced in [v1.1.16](https://github.com/ebaauw/homebridge-rpi/releases/tag/v1.1.16), back in October 2020 to deal with iOS14. I'll publish a fix later this weekend.
> 
> It looks like your accessory cache was cleared around 22:26, causing Homerbridge RPi to re-create the accessories instead of re-using the restored accessories. I think the multiple buttons might have continued to show, despite the bug, because they were created by an older version (before v1.1.16?).

If you can solve you’re a master :) :) :) 
Thank you so much
Waiting for the update ;)

**Comment by ebaauw** [comment]
In v1.3.7.
