### ISSUE TITLE
feature request: expose USB power as switch

### ISSUE THREAD

**Issue by zsolt-dev** [ebaauw/homebridge-rpi#117]
Hello,

I believe this could be a good use case:
Plug some small decorative lights into your RPI and turn them all on/off by killing power to the USB itself.

https://github.com/SkyJohn/Homebridge-Raspberry-Pi-USB-Power-Control

RPI has 4 USB ports which allow to draw up to 1.2 amps (for all 4 ports together).

Thank you

**Comment by ebaauw** [comment]
Interesting, didn't know about this.

The scripts from the above link work by simply writing `1-1` to `/sys/bus/usb/drivers/usb/unbind`, to disable the ports or to `/sys/bus/usb/drivers/usb/bind`, to (re-)enable them.  That would be easily implemented in Homebridge RPi, by whitelisting these files in `/opt/pigpio/access`.  I'd have to use `pigpiod` (even on the local Pi) as the files are writeable only by `root`.  As far as I can tell, there's no way to retrieve the current power state.  Also, the above link only mentions the Raspberry Pi 3B.

Testing this on the models I have:

Model | String | USB Device | USB Power| Ethernet
-- | -- | -- | -- | --
4B | `1-1` | Disables USB-2 devices on all four ports<br>USB-3 devices continue to work | Unaffected | Unaffected
4B | `2-1` | Disables USB-3 devices on the two USB-3 ports<br>USB-2 devices continue to work | Unaffected | Unaffected
3B+ | `1-1` | Disables USB devices on all four ports | Disabled | Disabled
3B | `1-1` | Disables USB devices on all four ports | Disabled | Disabled
Zero 2 W | `1-1` | Unaffected | Unaffected | n/a
Zero W | `1-1` | Unaffected | Unaffected | n/a

On the Zero W and Zero 2 W, I get a "write error: No such device", when no real USB device is connected, e.g. when only connecting a USB power meter and reading light.  Same for writing `2-1` on the Pi 4B when no USB-3 device is connected.  Note that a USB-2 extension cable will cause a USB-3 device to connect as a USB-2 device.

Different Raspberry Pi models have different USB design and behave differently in this aspect.  See also [this link](https://github.com/mvp/uhubctl#raspberry-pi-turns-power-off-on-all-ports-not-just-the-one-i-specified), which suggests the B+ and 2B should work like the 3B.  From the _Specifications_ table on the [Raspberry Pi Wiki](https://en.wikipedia.org/wiki/Raspberry_Pi), that would be the models with four USB 2.0 ports.

Concluding, it makes sense to expose USB power only on the models with four USB 2.0 ports, with a huge caveat that you need to connect them by WiFi, as disabling USB power also disables the Ethernet port.

I think it would make more sense semantically to support the USB ports as _Outlet_, rather than as (stateful) _Switch_.  This would enable you to select the type of the connected device (light, fan, or outlet) and appropriate icon in HomeKit.

**Comment by ebaauw** [comment]
Could you try beta v1.3.14-1.  See [Wiki](https://github.com/ebaauw/homebridge-rpi/wiki/Supported-Devices#usb-power) for details.

**Comment by zsolt-dev** [comment]
Thank you @ebaauw,

Oh wow, such a fast response. You are what makes this community amazing!

I have only RPI 4B and after some trial&error this is what what works for me:

1. install uhubctl
```
sudo apt-get install libusb-1.0-0-dev
git clone https://github.com/mvp/uhubctl
cd uhubctl
make
sudo make install
```
2. to turn off (without turning off the ethernet): `sudo uhubctl -l 1-1 -a off`
3. to turn on: `sudo uhubctl -l 1-1 -a on`
4. to get the status ('On' / 'Off'): `sudo uhubctl | grep 'Port 1' | head -n 1 |awk '{print $4}'`

Could you please implement it on RPI 4 according to this?

Thank you

**Comment by ebaauw** [comment]
> I have only RPI 4B and after some trial&error this is what what works for me:

Nice.  Seems to work here as well.  And does provide feedback for the current state.

> Could you please implement it on RPI 4 according to this?

Sorry, no.  Technically I could, but I don't want to.  It's too much work for too little benefits.

Implementing this for would require the user to download, compile, and install `uhubctl` on each Raspberry Pi.  I don't have the bandwidth to provide support for this.  Additionally, for each remote Raspberry Pi computer they would need a_ to install two additional scripts in `/opt/pigpiod/cgi`, one for power off and one for power on; and b) to adjust the `getState` script to run `uhibctl` and include its output in the `/tmp/getState.json`.  I don't have the bandwidth to support different configurations for different Pi models and different use cases (not everyone will want this functionality enabled).  Implementing this for a local Pi only, not using `pigpiod` would get rid of the `pigpiod` configuration, but would require the user running Homebridge to have password-less access to `sudo`.  Not something I can recommend nor support.
Also, there are already plugins out there that expose a HomeKit switch with shell scripts to report the switch state and act on turning the switch on or off, e.g. [homebridge-cmdswitch2](https://github.com/luisiam/homebridge-cmdswitch2).
