### ISSUE TITLE
Stop working on latest version with Rasbian 64 bit

### ISSUE THREAD

**Issue by aryajuanda** [ebaauw/homebridge-rpi#119]
Stop working on latest version on Rasbian 64 bit with homebridge 1.3.8

all GPIO switch is missing from accesories
<img width="1029" alt="Screen Shot 2021-11-30 at 19 36 45" src="https://user-images.githubusercontent.com/4106760/144051344-e0d9da5c-af6d-4c6a-8cd7-70ce1654f9d0.png">
version 1.3.15

install previous version work..
<img width="885" alt="Screen Shot 2021-11-30 at 19 55 04" src="https://user-images.githubusercontent.com/4106760/144051439-6985c35f-4f3d-40b4-82d7-ed40baf718bd.png">
version 1.3.13

**Comment by ebaauw** [comment]
Your system reports Debian, not Raspbian?
> [11/30/2021, 7:36:22 PM] [RPi] os: Debian GNU/Linux 10 (buster)

Homebridge RPi obtains this info is from `/etc/os-release`.  What’s the content of that file on your system?  How did you install the OS?

**Comment by aryajuanda** [comment]
I use rasbian lite 64 bit version from official raspberry repo.. 

I use raspberry for homebridge, pihole and openmediavault in a single raspberry pi 4B, i move to 64bit version few month ago..

![image](https://user-images.githubusercontent.com/4106760/144153452-f4df2dba-e2df-43ea-b477-cd59710c684a.jpeg)

**Comment by ebaauw** [comment]
Weird.  Never tried the 64-bit version myself.  Now busy migrating to bullseye - only found two breaking changes… so far in ser2net and in time synchronisation).  The 32-bit versions, both Full and Lite report `ID=raspbian` on stretch, buster, and bullseye.

Also interesting: `uname` reports processor architecture as `aarch64`, whereas NodeJS reports `arm64` (or Homebridge RPi wouldn’t have tried to read the Raspberry Pi model).
 
 I had hoped checking the OS would be a fail-fast approach before checking whether Homebridge RPi can actually invoke `vcgencmd`, but otherwise it doesn’t use any OS info.  I’ll relax the localhost checks on startup, since obviously Homebridge RPi had worked before on your system.

**Comment by ebaauw** [comment]
In v1.3.16.

**Comment by aryajuanda** [comment]
Homebridge RPI work again in 1.3.16 on 64bit version of rasbian
