### ISSUE TITLE
warning: got file handle 1

### ISSUE THREAD

**Issue by jwebbstevens** [ebaauw/homebridge-rpi#142]
```
[9/7/2022, 3:23:17 PM] [PiHole] PiHole Backup: set Frequency from 800MHz to 700MHz
[9/7/2022, 3:23:17 PM] [PiHole] PiHole Backup: set Load from 0.1 to 0.07
[9/7/2022, 3:23:32 PM] [PiHole] PiHole Backup: warning: got file handle 1
```

Got this error **warning: got file handle 1**.  Not sure what it means had a hard time finding anything referenced online about it other than that it has to do with this .js [PigpioClient.js](https://github.com/ebaauw/homebridge-rpi/blob/9cfe73ac9b2170a9d50d0cae0963cfdf13f96ecd/lib/PigpioClient.js)

any advice?

**Comment by ebaauw** [comment]
`pigpiod` gives out file handles in numerical order, starting at 0.  In your case, it returns file handle 1, meaning file handle 0 is already open.  If you have another client (e.g. another instance of Homebridge RPi running), this might be valid; otherwise it indicates a stale file handle.  In that case, close the file handle manually, or restart `pigpiod` to get rid of the warning.

**Comment by jwebbstevens** [comment]
amazing!  that worked. steps I used.

1. ssh to pihole
2. run '''sudo killall pigpiod'''
3. run '''sudo pigpiod'''
4. restart homebride.
