### ISSUE TITLE
problems with other accounts

### ISSUE THREAD

**Issue by applegamerho** [ebaauw/homebridge-rpi#167]
I restarted my raspberry due to problems other than Homebridge but again my family members' devices do not detect any Homebridge-RPI accessories. I previously read that connecting a device with iOS 15 solved it and it worked for me, but when I do it again it doesn't work and they remain "not responding" with other plugins it doesn't happen to me

I have everything in the latest version

I hope someone has the magic solution please

**Comment by ebaauw** [comment]
_Not Responding_ is caused by issues between Homebridge and the device running HomeKit, not by any plugin.  If only your family members see this, but you don’t, it’s probably your home hub; try power cycling that.  Otherwise, review your network settings, making sure your home hub and Apple devices see the mDNS announcements by Homebridge.

**Comment by alemicrorez** [comment]
I already tried changing the DNS and it doesn't work with any of them. 
It is strange since this plugin and the one from magichome are the only ones in which the accessories do not respond on my family's devices with an Apple ID different from mine since on my other iPhone and on my iPad they do work for me with my Apple id
