### ISSUE TITLE
Check for update seems to fail

### ISSUE THREAD

**Issue by SaschaRH** [ebaauw/homebridge-rpi#179]
Hi, 

starting this morning the check for updates fails:
[homebridge-rpi] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.

It might has something to do with the new version released  a few hours ago?

Kind regards,
Sascha

**Comment by ebaauw** [comment]
The error originates from the Homebridge UI, not from Homebridge RPi.  The check by Homebridge RPi itself works just fine.

I’ve also noted that the UI no longer displays my updated plugins correctly in the _Plugins_ tab.  The _Manage Versions_ and _Report An Issue_ entries are missing from the popup menu and the heart only shows an @ instead of the username (@ebaauw).  As far as I can tell, the NPM registry no longer lists `maintainers` with each version, and the UI doesn’t seem to cope with that correctly.

**Comment by ebaauw** [comment]
See https://github.com/homebridge/homebridge-config-ui-x/pull/2069.  Closing this issue.

**Comment by SaschaRH** [comment]
Thanks for clearing this up!

**Comment by ebaauw** [comment]
Workaround in v1.8.18.
