### ISSUE TITLE
Avoid saving to file

### ISSUE THREAD

**Issue by simont77** [ebaauw/homebridge-rpi#22]
Hi,
in my raspberry installation I limited as much as possible any unnecessary writing to the SD-Card to improve reliability. I notice that you write into the system log for every update of the raspberry power status. It seems also that to acquire data from the daemon you pass through an output file written by the daemon. Is it possible to implement everything in memory only?
Thanks

**Comment by ebaauw** [comment]
Neither Homebridge nor Homebridge RPi writes any log message to file: they're written to stdout (debug and log messages) and stderr (warning and error messages).  Depending on how you start Homebridge, these are redirected to a log file or to syslog.  If you don't want to write these to the SD card, change the service definition or startup script for Homebridge, to redirect these to RAM disk, external disk, or even `/dev/null` (which I wouldn't recommend, because you'll have no info for troubleshooting).

Homebridge RPi leverages (abuses if you want) the `pigpio` socket to communicate with the Pi being monitored.  That only allows a script to be started and a file to be read; there's no way to pass the output of a script.  

Implementing a custom service with another socket to pass this information without using a file on the remote Pi seems too much work.  I already got the question of Discord if the Pi accessory is needed at all, and if it would be possible to expose only the GPIO pins.  I think it would be, but I need to investigate; if possible, I'll add a config.json options to suppress the Pi accessory, and not call (or even require) the `vcgencmd` script.

Note that `vcgencmd` (called from the `vcgencmd` script) required elevated privileges, which I don't want to give to Homebridge.  So these commands need to be issued from another process.  If not called from `pigpio` (which runs under elevated privileges to access the GPIO pins), the script itself would need to be suid-ed.  That seems like a complex setup as well, so I decided not to create a special provision for monitoring the local Pi (the one Homebridge runs on).

I haven't tried to use a named pipe instead of a regular file for the `vcgencmd` script.  I'm not sure if that's handled entirely in memory, the named pipe is still a directory entry, but I suppose the contents woudn't be written to the SD card every heartbeat.  I could also change the location of the output file to `/tmp` or something, so you could use a RAM disk for that.

**Comment by simont77** [comment]
It's fine for me to have messages directed to syslog (for troubleshooting), however I would prefer to have there only one-time messages (e.g. at startup), or errors, not runtime Infos on regular updates. Would it be possible to add a parameter for homebridge-rpi verbosity level?

As for the file written by the daemon, I think it may be ok to give the ability to set a path, so that one could divert it to a ramdisk.

**Comment by ebaauw** [comment]
Please provide your thoughts on how best to provide a mechanism to change the level of logging to https://github.com/ebaauw/homebridge-lib/issues/26.

**Comment by ebaauw** [comment]
Next version will support changing the level of logging.  Also, the state of the local Raspberry Pi will be retrieved directly, without going through `pigpio` and an output file.  The output file will move to `/tmp`.  Making that configurable is easy on the Homebridge side, but needs to be reflected in the script and the `pigpio` configuration.  Maybe when I create an install/configure script, but for now it's too cumbersome.

**Comment by ebaauw** [comment]
In [v1.1.0](https://github.com/ebaauw/homebridge-rpi/releases/tag/v1.1.0).

**Comment by simont77** [comment]
Great!
