### ISSUE TITLE
Compatibility with Node.js v10.x

### ISSUE THREAD

**Issue by parautenbach** [ebaauw/homebridge-rpi#3]
I'm curious to use this plugin, but I'm unable to install it as my RPI 3B+ runs Raspbian (Debian Buster) and had v10 installed. 

After setting up homebridge with a number of plugins, I wanted to install this plugin, but got the dependency failure so I upgraded to v12. This, unfortunately (for reasons not quite known to me) borked my RPI Node.js installation so badly that I reverted to Node.js v10. 

Since `pigpiod` is running on my PI, is there any reason not to force this plugin to install under v10? Did you make v12 a dependency as it is what you tested with and feel comfortable with? Is there anything else I could try?

**Comment by parautenbach** [comment]
Just a follow-up question too: The docs require the use of `sudo` to install this. After reading a lot of docs, it seems preferable to not use `sudo` to install packages, so I've taken some care to follow these guidelines. Is there perhaps a reason you recommend using `sudo`? Is there some kind of root access required or a group I can add my `pi` (default user) to?

**Comment by ebaauw** [comment]
> I'm curious to use this plugin

Be advised its still under development.

> Did you make v12 a dependency as it is what you tested with and feel comfortable with?

I develop and test my plugins against the latest LTS release of NodeJS.  Recently, they moved from v10.16.3 to v12.13.0.  I'm not aware of any breaking changes between these versions, but I won't spend any time nor effort on checking this.

> is there any reason not to force this plugin to install under v10
> but got the dependency failure so I upgraded to v12.
> Is there anything else I could try?

I only issue warnings on version mismatches, but homebridge itself might be more strict.  You could patch the `package.json` file and specify a broader range for `node` under `engines` to silence homebridge.

> This, unfortunately (for reasons not quite known to me) borked my RPI Node.js installation so badly that I reverted to Node.js v10.

Note that after upgrading a major version of NodeJS, all C-modules need to be re-complied.  I've never written a package that contains C modules, so I don't know the details, but it seems the only sure way to force the re-compilation is thru uninstalling and re-installing the package.  Only my homebridge-p1 plugin uses a dependency (serialport) with a C-module.  homebridge-config-ui-x does.  homebridge itself used to, but no longer does.

> The docs require the use of `sudo` to install this.

This is needed to install packages globally (using `npm -g`), typically in `/usr/lib/node_modules` or `/usr/local/lib/node_modules`, so they're available to all users.  I suppose you could install the packages locally, under the user running homebridge, but I don't want to spend any time nor effort in figuring that out.  I do see a lot of issues with people having multiple (local vs global) NodeJS installations.

> it seems preferable to not use `sudo` to install packages

I definitely wouldn't run homebridge under `root` (using `sudo` or otherwise), but I see little harm in installing software under `root`.  Especially open source software, where you can inspect the code, if you don't trust it.

Note that @oznu is working on standardised homebridge setup instructions, see https://github.com/nfarina/homebridge/wiki. These are based on global installation as `root`.

**Comment by parautenbach** [comment]
Thank you for the comprehensive and quick answer. I'll digest it all and give feedback here on what worked (and didn't work).

**Comment by parautenbach** [comment]
Using the previous versions of the dependencies and installing using `sudo` did the trick. 

It would be nice if you could pin a release for a Node.js v10 version for others to use. 

```
$ git diff
diff --git a/package.json b/package.json
index db5f3a1..4b4dfcd 100644
--- a/package.json
+++ b/package.json
@@ -15,11 +15,11 @@
   "main": "index.js",
   "engines": {
     "homebridge": "^0.4.50",
-    "node": "^12.13.0"
+    "node": "^10.16.3"
   },
   "dependencies": {
     "bonjour-hap": "~3.5.4",
-    "homebridge-lib": "~4.4.6"
+    "homebridge-lib": "4.4.5"
   },
   "scripts": {
     "prepare": "standard",
```
