### ISSUE TITLE
Flow Sensor for water consumption

### ISSUE THREAD

**Issue by ih8ra1N** [ebaauw/homebridge-rpi#41]
Hi, how do I integrate ab waterfowl Sensor for measuring water consumption per Liter.
BR
Flo

**Comment by ebaauw** [comment]
I have no idea.  How do you connect the sensor?

**Comment by ih8ra1N** [comment]
Hi, it’s connected with an YF-S201 Chip on GPIO pin and switched by relay. I haven’t found a metric/ type to measure the water consumption. Here my current config:



    "accessories": [
        {
            "type": "airPressureSensor",
            "name": "flowsensor",
            "url": "http://192.168.1.5:1883",
            "mqttPubOptions": {
                "retain": false
            },
            "topics": {
                "getCurrentRelativeHumidity": "/Garden.Pi/WaterFlow",
                "getInUse": "/Garden.Pi/WaterFlow"
            },
            "startPub": [
                {
                    "topic": "/Garden.Pi/WaterFlow"
                }
            ],
            "integerValue": true,
            "history": true,
            "accessory": "mqttthing"
        }
    ],
    "platforms": [
        {
            "name": "RPi",
            "hosts": [
                {
                    "host": "localhost",
                    "name": "Raspberry",
                    "devices": [
                        {
                            "device": "valve",
                            "name": "Pumpe",
                            "gpio": 23,
                            "reversed": true
                        },
                        {
                            "device": "switch",
                            "name": "Flow Sensor",
                            "gpio": 13,
                            "reversed": true
                        }
                    ]
                }
            ],
            "platform": "RPi"

**Comment by ebaauw** [comment]
I take it, the `valve` device is the relay to switch the pump on and off?  That should already work?

`switch` is an output device (like `valve`), so that won't work with a sensor.  Could you try and configure a `button` device for the flow sensor?  You should see the button activate on each pulse sent by the YF-S201.  I have no idea what rate of pulses to expect, the `button` has a hardcoded debounce time of 20ms, so it should work as long as the rate is (well) below 50 pulses per second.

If that works, we would have to convert the pulses to litres for total water consumption.  I suppose that would be a config.json parameter.  I don't think HomeKit defines any standard characteristic for water consumption.  I'm not sure I understand the Eve Aqua well enough to expose the sensor as such.  Alternatively, I could expose abuse _Total Consumption_ for electricity (as I do for the Gas meter in Homebridge P1).  This will cause Eve to show kWh instead of l, but it will expose history.

**Comment by ebaauw** [comment]
Closing since I don't get the asked info.
