### ISSUE TITLE
Voltage reporting improvement

### ISSUE THREAD

**Issue by RobBuijs** [ebaauw/homebridge-rpi#71]
Hi,

You might want to update the plugin a bit (sorry no patch or PR) :

Use "Characteristic: this.Characteristics.eve.Voltage" so voltage is shown with the correct voltage icon in Eve (like it does in the P1 plugin). Also if you *1000 the voltage and then use mV as data unit instead of V, the plugin will show three decimals for a much more precise reporting of the measurement.

**Comment by ebaauw** [comment]
This is really an issue with the Eve app.

> Use "Characteristic: this.Characteristics.eve.Voltage"

Did you actually try that?  Last time I did, Eve rounded the display value to V, which is even less informative.  That's why I created a separate _CPU Voltage_ characteristic.

> the plugin will show three decimals for a much more precise reporting of the measurement.

If you check the log, you'll see that Homebridge RPi already sets the voltage in mV precision.  It's Eve that rounds the displayed value.
> [11/12/2020, 14:56:08] [RPi] pi1: set Voltage from 1.2V to 1.375V

I suppose I could re-define the CPU Voltage characteristic to mV and use integer values.  I cannot re-define the unit of the Eve characteristic.

**Comment by RobBuijs** [comment]
I did try. In a hacky way, but I got it working. see screenshot. Just a restart of homebridge and the eve app was needed to get it in this state. I’ll work to create a proper PR from it.

![B3EC1271-7A1C-4458-AA50-EFFF857BBB58](https://user-images.githubusercontent.com/15612312/101957084-0adfb900-3c01-11eb-9ae5-4cdf7dba5679.png)

**Comment by ebaauw** [comment]
But now it reports 1362 V instead of 1.362 V.

**Comment by RobBuijs** [comment]
> But now it reports 1362 V instead of 1.362 V.

Shoot, that’s a dot.

**Comment by RobBuijs** [comment]
Doesn’t work as I thought it did. M
