### ISSUE TITLE
 “servo” as a window service

### ISSUE THREAD

**Issue by leehadassin** [ebaauw/homebridge-rpi#94]
Hi,

Love the plug-in.
Just wondering if it was possible if the servo could be made a window service or one of the other similar services (window covering or slats).
I understand this is a big change. 
I am using the servo for pan/tilt of a camera, but the control is clunky in the eve app.
A couple other plugins I use have the window service type and it shows up in the native home.app as sliders similar to dimmable lights.
Understand if this isn’t feasible/important.
Thanks again for the great plug-in.

cheers

Lee

**Comment by ebaauw** [comment]
It would be a relative small change to Homebridge RPi code, but I doubt it would make sense functionally.

_Slat_ seems to make most sense semantically: it's got _Current Tilt Angle_ and _Target Tilt Angle_ as optional characteristics.  I would have to expose (mandatory) _Slat Type_ and _Current Slat State_, which would be fixed to _Horizontal_ and _Fixed_.  It doesn't have _On_ or something equivalent to enable/disable the servo.  However, it doesn't seem to be supported by Home on iOS 14.5.1?!

_Window Covering_ makes less sense: it requires mandatory _Current Position_ and _Target Position_ in addition to optional _Current Horizontal Tilt Angle_ and _Target Horizontal Tilt Angle_.  It doesn't have _On_ or something equivalent to enable/disable the servo either.  The tile in Home controls the position, not the tilt angle.  The tilt angle can be controlled from Home (from the _Settings_ of the service), but it doesn't seem to refresh.  Could be caused by the HomeKit Accessory Simulator, I guess.   I could add an _Enabled_ to turn the servo on or off, but that wouldn't be controllable from Home (unless you use a HomeKit scene defined in Eve).
If I were to map the tilt to the position, it would be limited to 0% to 100% instead of to -90° to 90°.  And it wouldn't turn on/off the servo, even though the tile would suggest that.

There used to be a _Camera Control_ service, with mandatory _On_ and optional tilt characteristics, but that's no longer supported, according to a comment in the HAP-NodeJS code.

**Comment by leehadassin** [comment]
Thanks for looking at this. 

To me, having an enable/disable separate from the target/current angle isn't an issue (I'm driving small hobbyist servos direct from the Pi and as long as I stay within 0-88deg it doesn't buzz) but I understand this could be for others.

Thanks again.
